# Generated by Django 3.0.3 on 2020-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituredetail',
            name='category',
            field=models.CharField(choices=[('food', '食費'), ('fare', '交通費'), ('medical', '医療費'), ('tuition', '学費'), ('amusement', '娯楽費'), ('tax', '税金'), ('communication', '通信費'), ('clothes', '衣料品'), ('others', '雑費')], max_length=100),
        ),
    ]
