# Generated by Django 3.0.3 on 2020-09-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilityfee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilityfee',
            new_name='Money',
        ),
    ]
